steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/snapcat-api:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/snapcat-api:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "snapcat-api"
      - "--image=gcr.io/$PROJECT_ID/snapcat-api:$COMMIT_SHA"
      - "--region=us-central1"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=JWT_SECRET_KEY=jwt_secret_key:latest,DATABASE_URL=database_url:latest,EMAIL_USER=email_user:latest,EMAIL_PASS=email_pass:latest"
images:
  - "gcr.io/$PROJECT_ID/snapcat-api:$COMMIT_SHA"
logsBucket: "gs://snapcat-cc-bucket/logs"